import { YukioItem } from './types';

// This is the master list of all YUKIO items.
export const YUKIO_LIST: YukioItem[] = [
  {
    id: "Y001",
    name: "玉子壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_tamago.jpg",
  },
  {
    id: "Y002",
    name: "三文魚籽壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_ikura.jpg",
  },
  {
    id: "Y003",
    name: "鯖魚壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_saba.jpg",
  },
  {
    id: "Y004",
    name: "蝦壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_ebi.jpg",
  },
  {
    id: "Y005",
    name: "鯛魚壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_tai.jpg",
  },
  {
    id: "Y006",
    name: "三文魚壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_salmon.jpg",
  },
  {
    id: "Y007",
    name: "海膽壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_uni.jpg",
  },
  {
    id: "Y008",
    name: "呑拿魚壽司",
    category: "壽司系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_sushi_maguro.jpg",
  },
  {
    id: "Y009",
    name: "企鵝",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_penguin.jpg",
  },
  {
    id: "Y010",
    name: "兔仔",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_usagi.jpg",
  },
  {
    id: "Y011",
    name: "小雞",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_hiyoko.jpg",
  },
  {
    id: "Y012",
    name: "水滴仔",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_shizuku.jpg",
  },
  {
    id: "Y013",
    name: "犬",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_inu.jpg",
  },
  {
    id: "Y014",
    name: "美人魚",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_amabie.jpg",
  },
  {
    id: "Y015",
    name: "鯊魚",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_same.jpg",
  },
  {
    id: "Y016",
    name: "黑貓",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_nekosuke.jpg",
  },
  {
    id: "Y017",
    name: "必勝御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio-omamori-red.jpg",
  },
  {
    id: "Y018",
    name: "合格御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_omamori_blue.jpg",
  },
  {
    id: "Y019",
    name: "健康御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_omamori_green.jpg",
  },
  {
    id: "Y020",
    name: "幸福御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_omamori_yellow.jpg",
  },
  {
    id: "Y021",
    name: "金運御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_omamori_money.jpg",
  },
  {
    id: "Y022",
    name: "縁結び御守",
    category: "御守系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_omamori_pink.jpg",
  },
  {
    id: "Y023",
    name: "帰宅部",
    category: "PICO 系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/picpic_kitakubu.jpg",
  },
  {
    id: "Y024",
    name: "青鳥",
    category: "動物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yuki_aoitori_1.jpg",
  },
  {
    id: "Y025",
    name: "粉紅海星",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_hitode_omote.jpg",
  },
  {
    id: "Y026",
    name: "螢光魷魚發光體",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_hotaruika.jpg",
  },
  {
    id: "Y027",
    name: "紫色魷魚",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_ika_omote.jpg",
  },
  {
    id: "Y028",
    name: "小丑魚",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_kakurekumanomi_omote.jpg",
  },
  {
    id: "Y029",
    name: "海龜BB",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_kame.jpg",
  },
  {
    id: "Y030",
    name: "皇帝企鵝",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_kouteipengin_omote.jpg",
  },
  {
    id: "Y031",
    name: "你好普通人",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_plane_omote.jpg",
  },
  {
    id: "Y032",
    name: "美白雷鳥",
    category: "動物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_raicyo.jpg",
  },
  {
    id: "Y033",
    name: "鯊魚",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_same_omote.jpg",
  },
  {
    id: "Y034",
    name: "白蝦",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_shiroebi_n.jpg",
  },
  {
    id: "Y035",
    name: "老虎",
    category: "動物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_tora.jpg",
  }
  {
    id: "Y036",
    name: "女朋友",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_kanojo.jpg",
  },
  {
    id: "Y037",
    name: "粉紅豬",
    category: "動物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukiobuta.jpg",
  },
  {
    id: "Y038",
    name: "織田信長",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_nobunaga.jpg",
  },
  {
    id: "Y039",
    name: "豐臣秀吉",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_hideyoshi.jpg",
  },
  {
    id: "Y040",
    name: "德川家康",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_tokugawa.jpg",
  },
  {
    id: "Y041",
    name: "乒乓球",
    category: "人物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_mc_takkyu.jpg",
  },
  {
    id: "Y042",
    name: "紅色鯛魚",
    category: "海洋系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_tai.jpg",
  },
  {
    id: "Y043",
    name: "貓頭鷹",
    category: "動物系列",
    imageUrl: "https://raw.githubusercontent.com/hiiamalieny/yukiocollection/main/public/images/yukio_hukurou.jpg",
  },
];
